gamedata/scripts/western_goods_utils.script

Added a function to iterate through and execute a function on each member of a squad;

feature(squad-iter): Squad Iteration Function

---

gamedata/scripts/western_goods_core.script

Fixed incorrect addon version.

fix(addon-version): Fixed Addon Version

---

README.md
gamedata/configs/text/eng/st_western_goods_mcm.xml
gamedata/configs/text/rus/st_western_goods_mcm.xml
gamedata/scripts/western_goods_mcm.script

**• Additions:**
> • Added native integration with [Device Selector Key](https://www.moddb.com/mods/stalker-anomaly/addons/mcm-required-device-selector-key).

feature(dev-key-select-patch): Device Selector Key Native Integration

---

gamedata/configs/ui/textures_descr/ui_western_goods_readables.xml

**• Bug fixes:**
> • Fixed missing texture descriptions for two of the quest items.

fix(readables): Fixed Readable Quest Items

---

CHANGELOG.md
README.md

- Fixed missing author ship from Parazit

fix(author-parazit): Fix loss of authorship

---

gamedata/scripts/western_goods_trade_eur_usd.script
gamedata/scripts/western_goods_utils.script

> • Fixed small lag caused by repeated calls made to western_goods_utils.get_character_id(game_object) (Thanks Sark);

fix(inventory-lag): Inventory Lag Fix

---

gamedata/scripts/western_goods_ui_gps_locator.script
gamedata/scripts/western_goods_ui_rangefinder.script
gamedata/scripts/western_goods_ui_readable.script

> • Renamed variables;
> • Changed locals to class members;
> • Restructured some bits of code to use Return-Early pattern.

feature(class-members): LUA Class Members

---

gamedata/scripts/modxml_western_goods_barter_ui.script
gamedata/scripts/modxml_western_goods_character_desc_deadcity.script
gamedata/scripts/modxml_zzz_rand_text_dialog.script

• Changes :
>    - Cleaned up and improved safety DXML scripts;

feature(dxml-checks): Stricter DXML Checks

---

gamedata/scripts/western_goods_core.script
gamedata/scripts/western_goods_utils.script

• Additions:
>    - Added checks against missing translations;

feature(safe-translations): Safe Translations

---

gamedata/scripts/modxml_western_goods_barter_ui.script
gamedata/scripts/modxml_western_goods_character_desc_deadcity.script

• Bug fixes :
>    - Fixed broken DXML query (that was used for testing a new feature);
>    - Improved warning messages;

fix(dxml): Fixed DXML Query

---

gamedata/configs/plugins/mod_actor_effects_western_goods.ltx

• Changes :
>    - Removed some camera animations for items that are too small to justify sitting through an anim;

fix(cam-anims): Removed Some Camera Animations

---

gamedata/configs/ui/textures_descr/ui_devices_western_goods.xml
gamedata/scripts/western_goods_ui_gps_locator.script

> • Added support for New Levels for the GPS Locator;
> • Optimized GPS Locator code;

feature(dev-gps): GPS Improvements

---

gamedata/configs/items/settings/mod_parts_western_goods.ltx
gamedata/configs/items/weapons/m_rangefinder.ltx

> • Fixed rangefinder being marked as repairable by helmet repair kits;
> • Fixed rangefinder not having parts;
> • Fixed lighter not having parts;

fix(parts-repairs): Fixed Deices Parts & Repairs

---

gamedata/scripts/western_goods_npcs.script
gamedata/scripts/western_goods_utils.script

> • Made a helper function to avoid calling get_object_squad with actor game_object.

feature(on-enemy-eval): 'on_enemy_eval' Improvements

---

gamedata/scripts/western_goods_core.script

> • Adjusted loot params for Bic lighter and rangefinder;

feature(loot-params): Adjust Loot Params

---

gamedata/scripts/modxml_western_goods.script
gamedata/scripts/western_goods_ui_lighter.script

> • Added ability for the lighter to turn on Hideout Furniture's gas lamp item;

feature(dev-lighter-hf): Lighter Compatibility Hideout Furniture

---

README.md
gamedata/configs/plugins/mod_pda_trade_items_western_goods.ltx

> • Added support for ama-zone. Western Goods items will now be available in the list.

feature(ama-zone): Add support for ama-zone

---

gamedata/configs/items/weapons/m_rangefinder.ltx

**• Bug fix :**
> • Fixed rangefinder having infinite zoom (Thanks Motorolª).

fix(dev-rangefinder): Fixed Rangefinder Zoom

---

gamedata/scripts/western_goods_bind_fire_source.script
gamedata/scripts/western_goods_bind_lighter.script
gamedata/scripts/western_goods_bind_object.script
gamedata/scripts/western_goods_monkey_patches.script

> • Fixed not being able to light cigarettes without FDDA;
> • Fixed multiple lighters (in inventory) being used when lighting cigarettes;
> • Fixed object_binder_wrapper not properly delegating calls to wrapped class;
> • Fixed lose references to the binder making it outlive the object it is bound to.

fix(dev-lighter): Lighter Fixes

---

gamedata/scripts/western_goods_loot.script
gamedata/scripts/western_goods_monkey_patches.script
gamedata/scripts/western_goods_trade_eur_usd.script
gamedata/scripts/western_goods_ui_gps_locator.script
gamedata/scripts/western_goods_ui_readable.script

> • Changed monkey-patches to use a new system able to dynamically resolve the correct monkey-patch to apply.

feature(monkey-patches): Port Monkey-Patches To New System

---

gamedata/scripts/western_goods_bind_lighter.script

> • Fixed lighter's fuel level not persisting through saves;

fix(dev-lighter): Fix Lighter Fuel Level

---

gamedata/scripts/western_goods_core.script
gamedata/scripts/western_goods_mcm.script

> • Removed compass code that isn't supposed to be in develop branch;
> • Added new functions to check if MCM & Device Selector Key addons are installed;

fix(remove-compass-code): Remove Compass Code

---

gamedata/scripts/western_goods_ui_gps_locator.script
gamedata/scripts/western_goods_ui_rangefinder.script
gamedata/scripts/western_goods_utils.script

> • Added utility function to convert one or multiple strings to one or multiple digit textures;
> • Back-ported the new utility function to the GPS and Rangefinder codes;
> • Fixed rangefinder code referring to itself through 'GUI' singleton instead of 'self';

feature(3d-uis-digits): 3D UI Digits

---

gamedata/scripts/western_goods_bind_lighter.script

> • Fixed lighter playing animation even when it wasn't selected to light up the campfire/gas lamp.

fix(dev-lighter): Fix Lighter Issues

---

gamedata/configs/text/eng/st_western_goods_core.xml
gamedata/configs/text/rus/st_western_goods_core.xml
gamedata/scripts/western_goods_bind_fire_source.script
gamedata/scripts/western_goods_bind_lighter.script
gamedata/scripts/western_goods_monkey_patches.script
gamedata/scripts/western_goods_ui_readable.script
gamedata/scripts/western_goods_utils.script

> • Lighter now displays its fuel level in the item description;
> • Clean-up of unused translation strings, and refactor of a few monkey-patches;

feature(dev-lighter): Lighter Description Header

---

gamedata/configs/gameplay/character_desc_western_goods.xml
gamedata/configs/gameplay/dialogs_western_goods.xml
gamedata/configs/mod_named_locations_western_goods.ltx
gamedata/configs/plugins/western_goods/guides/guides_western_goods.ltx
gamedata/configs/plugins/western_goods/guides/importer.ltx
gamedata/configs/text/eng/st_western_goods_core.xml
gamedata/configs/text/eng/st_western_goods_dialogs.xml
gamedata/configs/text/eng/st_western_goods_named_locations.xml
gamedata/configs/text/rus/st_western_goods_core.xml
gamedata/configs/text/rus/st_western_goods_dialogs.xml
gamedata/configs/text/rus/st_western_goods_named_locations.xml
gamedata/scripts/western_goods_dialogs_manager.script
gamedata/scripts/western_goods_flea.script
gamedata/scripts/western_goods_guide.script
gamedata/scripts/western_goods_helicopter_transport.script
gamedata/scripts/western_goods_npcs.script
gamedata/scripts/western_goods_trade_eur_usd.script
gamedata/scripts/western_goods_utils.script

> • Completely rewrote the guide system to allow it to be used dynamically by multiple NPCs;
> • Adapted the helicopter transport system to use the new guide system;
> • Added ability for Ashot (Jupiter), Professor Ozersky (Jupiter) and Peregrine (Yantar) to guide the player.

feature(guide-system): Rework Guide System

---

CHANGELOG.md
src/guides/gamedata/configs/plugins/western_goods/guides/guides_western_goods.ltx

> • Changed guide price from Yanov to Army Warehouses from 4k RUB to 6k RUB (Thanks Rambito);
> • Changed guide price from Yanov to Yantar from 8k RUB to 12k RUB (Thanks Rambito);
> • Changed guide price from Yantar to Yanov from 8k RUB to 12k RUB (Thanks Rambito);

feature(guides-prices-rebalance): Rebalance Guide Prices

---

CHANGELOG.md
README.md
src/core/gamedata/configs/text/eng/st_western_goods_mcm.xml
src/core/gamedata/configs/text/rus/st_western_goods_mcm.xml
src/core/gamedata/scripts/western_goods_core.script
src/core/gamedata/scripts/western_goods_mcm.script

> • Dropped support for Device Selector Key addon;

feature(drop-dsk-support): Drop support for Device Selector Key addon

---

src/readables/gamedata/configs/items/settings/mod_parts_western_goods_readables.ltx

> • Fixed magazines not having parts, preventing the player from disassembling them (Thanks Minolta50);

fix(magazines-parts): Add Parts To Magazines

---

src/core/gamedata/configs/text/eng/st_western_goods_core.xml
src/core/gamedata/configs/text/rus/st_western_goods_core.xml
src/core/gamedata/scripts/western_goods_helicopter.script
src/devices/gamedata/scripts/western_goods_ui_gps_locator.script
src/storylines/gamedata/scripts/western_goods_tasks_act_2.script

> • Added translations to map spots placed by the addon;

feature(map-spots-i18n): Translate Map Spots

---

src/core/gamedata/configs/text/eng/st_western_goods_mcm.xml
src/core/gamedata/configs/text/fra/st_western_goods_mcm.xml
src/core/gamedata/configs/text/rus/st_western_goods_mcm.xml
src/core/gamedata/scripts/western_goods_class_light_source.script
src/core/gamedata/scripts/western_goods_mcm.script
src/guides/gamedata/configs/text/fra/st_western_goods_named_locations_guides.xml

> • Added options to increase lighter range and brightness in MCM (Thanks Rambito).

feature(lighter-mcm): Add Customizable Lighter Brightness/Range In MCM

---

src/devices/gamedata/configs/items/items/items_western_goods_tech.ltx

Compatibility with Fatal Error Addon.

Update items_western_goods_tech.ltx to make it compatible with Fatal Error Addon.
